name: Run tests (Node)

on: push

concurrency:
  group: "tests-node"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm x tsc

      - name: Copy non-TypeScript files
        run: npm run copy-files

      - name: Run tests
        run: npm test
